name: telleo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  advance_notification: ^1.0.5
  auto_route: ^3.1.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_hooks: ^0.18.1
  flutter_signin_button: ^2.0.0
  freezed_annotation: ^1.0.0
  gap: ^2.0.0
  get_it: ^7.2.0
  injectable: ^1.5.0
  json_annotation: ^4.3.0
  logger: ^1.1.0
  shared_preferences: ^2.0.9
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  uuid: ^3.0.5

dev_dependencies:
  auto_route_generator: ^3.1.0
  bloc_test: ^9.0.1
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.0.0
  injectable_generator: ^1.5.2
  json_serializable: ^6.0.1
  mockito: ^5.0.16
  test: ^1.16.0

flutter:
  uses-material-design: true

  assets:
    - assets/
